services:
  dd-agent:
    image: datadog/agent:7
    container_name: dd-agent
    networks:
      - observability
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_SITE: ${DD_SITE}
      DD_APM_ENABLED: "true"
      DD_LOGS_ENABLED: "true"
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    ports:
      - "8126:8126"
  customers-service:
    container_name: customers-service
    build:
      context: ./Customer.Service.API
    ports:
      - 2201:8080
    networks:
      - observability
    environment:
      - CORECLR_ENABLE_PROFILING=1
      - CORECLR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}
      - CORECLR_PROFILER_PATH=/opt/datadog/Datadog.Trace.ClrProfiler.Native.so
      - DD_DOTNET_TRACER_HOME=/opt/datadog
      - DD_SERVICE=customers.service.api
      - DD_ENV=dev
      - DD_AGENT_HOST=dd-agent
  order-service:
    container_name: orders-service
    build:
      context: ./Order.Service.API
    ports:
      - 2202:8080
    networks:
      - observability
    environment:
      - CORECLR_ENABLE_PROFILING=1
      - CORECLR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}
      - CORECLR_PROFILER_PATH=/opt/datadog/Datadog.Trace.ClrProfiler.Native.so
      - DD_DOTNET_TRACER_HOME=/opt/datadog
      - DD_SERVICE=order.service.api
      - DD_ENV=dev
      - DD_AGENT_HOST=dd-agent
  inventory-service:
    container_name: inventory-service
    networks:
      - observability
    build:
      context: ./Inventory.Service.API
    ports:
      - 2203:8080
    environment:
      - CORECLR_ENABLE_PROFILING=1
      - CORECLR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}
      - CORECLR_PROFILER_PATH=/opt/datadog/Datadog.Trace.ClrProfiler.Native.so
      - DD_DOTNET_TRACER_HOME=/opt/datadog
      - DD_SERVICE=inventory.service.api
      - DD_ENV=dev
      - DD_AGENT_HOST=dd-agent
networks:
  observability:
    driver: bridge
